[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
plugins = ["pydantic.mypy"]
ignore_missing_imports = true

[project]
name = "srb"
version = "0.0.6.1"
description = "Robot Learning Beyond Earth"
authors = [{ name = "Andrej Orsula", email = "orsula.andrej@gmail.com" }]
maintainers = [{ name = "Andrej Orsula", email = "orsula.andrej@gmail.com" }]
urls = { Repository = "https://github.com/AndrejOrsula/space_robotics_bench", Documentation = "https://AndrejOrsula.github.io/space_robotics_bench" }
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Rust",
  "License :: OSI Approved :: MIT License",
  "License :: OSI Approved :: Apache Software License",
  "Framework :: Robot Framework",
]
keywords = ["benchmark", "robotics", "simulation", "space"]
readme = "README.md"
license = { text = "MIT OR Apache-2.0" }
requires-python = "==3.12.*"
dependencies = [
  ## Core
  "gymnasium",
  # "isaaclab~=3.0",
  "oxidasim~=0.1",
  ## Assets
  ##"simforge[assets]",
  ## Typing
  "pydantic",
  ## Serialization
  "orjson",
  ##"torch==2.11",
  ##"torchvision==0.26.0",
  ##"isaacsim[all,extscache]==6.0.1.0",
]

[project.optional-dependencies]
all = [
  ## Algorithms
  "srb[algo]",
  ## Hardware
  "srb[hw]",
  ## Logging
  "srb[logging]",
  ## Utils
  "srb[cli]",
  "srb[dev]",
]
## Algorithms
algo = [
  #
  "srb[dreamer]",
  "srb[sb3]",
  "srb[sbx]",
  "srb[skrl]",
  "srb[robomimic]",
  "srb[policyflow]",
]
dreamer = [
  #
  # Note: Only editable install of dreamer works for now (circular import of  partially initialized module included with sys.path)
  # TODO[mid]: Fix Dreamer install (fork and fix recursive import)
  # "dreamer@git+https://github.com/AndrejOrsula/dreamerv3.git@4049794d4135e41c691f18da38a9af7541b01553",
  # Note: jax==0.5.1 causes issues
  "jax~=0.4,<0.5.1",
]
sb3 = [
  #
  "stable-baselines3~=2.9",
  "sb3-contrib~=2.9",
  # Note: The fork relaxes the dependency for gymnasium (shimmy requires gymnasium>=1.0)
  # "rl_zoo3@git+https://github.com/AndrejOrsula/rl-baselines3-zoo.git@e04921b4ccbadbc9f6bcc46cc1787ffc1d2c8963",
]
sbx = [
  #
  "sbx-rl~=0.23",
  "tf_keras~=2.21",
]
skrl = [
  #
  "skrl~=2.0",
]
robomimic = [
  #
  # "robomimic@git+https://github.com/ARISE-Initiative/robomimic.git@TODO",
]
policyflow = [
  #
  # Install PolicyFlow from local repo: cd ~/PolicyFlow_srb/policyflow && pip install -e .
  "einops~=0.6",
]
## Hardware
hw = [
  #
  "srb[spacemouse]",
]
spacemouse = [
  #
  "pyspacemouse~=1.0",
]
## Logging
logging = [
  #
  "srb[wandb]",
  "srb[tensorboard]",
]
wandb = [
  #
  "wandb~=0.19",
]
tensorboard = [
  #
  "tensorboard~=2.0",
  "tensorflow~=2.0",
]
## Utils
cli = [
  #
  "srb[rich]",
  "srb[repl]",
  "argcomplete~=3.0",
  "hydra-core~=1.0",
  "omegaconf~=2.0",
]
dev = [
  #
  "srb[test]",
  "srb[tracing]",
  "srb[typing]",
  "srb[plots]",
]
rich = [
  #
  "rich~=15.0",
]
test = [
  #
  "pytest~=8.0",
  "pytest-order~=1.0",
  "pytest-sugar~=1.0",
]
tracing = [
  #
  "srb[rich]",
  "logfire~=4.0",
]
typing = [
  #
  "mypy~=1.0",
  "types-psutil~=7.0",
  "types-PyYAML~=6.0",
  "types-toml~=0.10",
]
repl = [
  #
  "ptpython~=3.0",
]
plots = [
  #
  "seaborn~=0.13",
]

[tool.uv]
no-build-isolation-package = ["idna-ssl"]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }
isaacsim = {index = "isaac" }

[[tool.uv.index]]
name = "pypi"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "isaac"
url = "https://pypi.nvidia.com"
explicit = true




[project.scripts]
space_robotics_bench = "srb.__main__:main"
srb = "srb.__main__:main"
